config/routes.rb
Todo::Application.routes.draw do
  resources :projetos

  resources :tarefas

  root :to => 'tarefas#index'

end

app/models/projeto.rb
#enconding: utf-8
class Projeto < ActiveRecord::Base
  attr_accessible :cliente, :data_fim, :data_inicio, :descricao, :nome

  validates_presence_of :nome
  validate :validate_presence_of_data_inicio_menor_igual_a_data_fim
  validate :primeira_letra_maiuscula
  validates :nome, :uniqueness => true
 
  has_many :tarefas

  private
  
  def validate_presence_of_data_inicio_menor_igual_a_data_fim
  	if data_inicio > data_fim
  		errors.add(:data_inicio, "nao pode ser maior do que data fim")
  	end
  end

  def primeira_letra_maiuscula
  	errors.add(:nome, "Primeira letra do nome deve ser maiuscula") unless nome =~ /^[A-Z].*/
  end

end

app/models/tarefa.rb
class Tarefa < ActiveRecord::Base
  attr_accessible :data_fim, :descricao, :responsavel, :nome, :projeto_id

  validates_presence_of :responsavel

  belongs_to :projeto

  def nome_do_projeto
  	return "sem projeto" if projeto.nil?
  	projeto.nome
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projetos }
      format.xml { render xml: @projetos }
    end
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
    @projeto = Projeto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @projeto }
    end
  end

  # GET /projetos/new
  # GET /projetos/new.json
  def new
    @projeto = Projeto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @projeto }
    end
  end

  # GET /projetos/1/edit
  def edit
    @projeto = Projeto.find(params[:id])
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(params[:projeto])

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto was successfully created.' }
        format.json { render json: @projeto, status: :created, location: @projeto }
      else
        format.html { render action: "new" }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projetos/1
  # PUT /projetos/1.json
  def update
    @projeto = Projeto.find(params[:id])

    respond_to do |format|
      if @projeto.update_attributes(params[:projeto])
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto = Projeto.find(params[:id])
    @projeto.destroy

    respond_to do |format|
      format.html { redirect_to projetos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController

	def new
		@tarefa = Tarefa.new
	end

	def index
		#@tarefas = Tarefa.all
		@tarefas = Tarefa.includes(:projeto).all
	end

	def create
		@tarefa = Tarefa.new(params[:tarefa])
		if @tarefa.save
			flash[:notice] = "Tarefa criada com sucesso"
			redirect_to tarefas_path
		end
	end

	def edit
		@tarefa = Tarefa.find(params[:id])
	end

	def update
		@tarefa = Tarefa.find(params[:id])
		if @tarefa.update_attributes(params[:tarefa])
			flash[:notice] = "Tarefa #{@tarefa.nome} atualizada com sucesso"
			redirect_to tarefas_path
		else
			flash[:notice] = @tarefa.errors.messages
			redirect_to edit_tarefa_path
		end

	end

	def destroy
		@tarefa = Tarefa.find(params[:id])
		@tarefa.destroy
		flash[:notice] = "Voce destrui a tarefa #{@tarefa.nome}"
		redirect_to tarefas_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper

	def link_para_o_projeto(tarefa)
		return "sem projeto" if tarefa.projeto.nil?
		link_to tarefa.nome_do_projeto , projeto_path(tarefa.projeto)
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projetos/_form.html.erb
<%= form_for(@projeto) do |f| %>
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :data_inicio %><br />
    <%= f.date_select :data_inicio , :order => [:day, :month, :year]  %>
  </div>
  <div class="field">
    <%= f.label :data_fim %><br />
    <%= f.date_select :data_fim , :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br />
    <%= f.text_field :cliente %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projetos/edit.html.erb
<h1>Editing projeto</h1>

<%= render 'form' %>

<%= link_to 'Show', @projeto %> |
<%= link_to 'Back', projetos_path %>

app/views/projetos/index.html.erb
<h1>Listing projetos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Data inicio</th>
    <th>Data fim</th>
    <th>Cliente</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projetos.each do |projeto| %>
  <tr>
    <td><%= projeto.nome %></td>
    <td><%= projeto.data_inicio %></td>
    <td><%= projeto.data_fim %></td>
    <td><%= projeto.cliente %></td>
    <td><%= projeto.descricao %></td>
    <td><%= link_to 'Show', projeto %></td>
    <td><%= link_to 'Edit', edit_projeto_path(projeto) %></td>
    <td><%= link_to 'Destroy', projeto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Projeto', new_projeto_path %>
<br/><br/>
<%= link_to "Tarefas" , tarefas_path %>

app/views/projetos/new.html.erb
<h1>New projeto</h1>

<%= render 'form' %>

<%= link_to 'Back', projetos_path %>

app/views/projetos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @projeto.nome %>
</p>

<p>
  <b>Data inicio:</b>
  <%= @projeto.data_inicio %>
</p>

<p>
  <b>Data fim:</b>
  <%= @projeto.data_fim %>
</p>

<p>
  <b>Cliente:</b>
  <%= @projeto.cliente %>
</p>

<p>
  <b>Descricao:</b>
  <%= @projeto.descricao %>
</p>
<br/>
<hr/>
<h3>Tarefas</h3>
<table>
    <tr>
      <th>Nome</th>
      <th>Responsavel</th>
      <th>Descrição</th>
      <th>Data de Entrega</th>
    </tr>
    <% @projeto.tarefas.each do |tarefa| %>
      <tr>
        <td><%= tarefa.nome %></td>
        <td><%= tarefa.responsavel %></td>
        <td><%= tarefa.descricao %></td>
        <td><%= tarefa.data_fim %></td>
      </tr>
    <% end %>
</table>
<hr/>


<%= link_to 'Edit', edit_projeto_path(@projeto) %> |
<%= link_to 'Back', projetos_path %>

app/views/tarefas/_form.html.erb
	<%= form_for @tarefa do |f| %>
		<p>
			<%= f.label "Nome" %> <br/>
			<%= f.text_field :nome %>
		</p>
		<p>
			<%= f.label "Descrição" %> <br/>
			<%= f.text_area :descricao, :rows => 10 %>
		</p>
		<p>
			<%= f.label "Responsável" %>
			<%= f.text_field :responsavel %>
		</p>
		<p>
			<%= f.label "Data Conclusão" %>
			<%= f.date_select :data_fim, :start_year => Time.now.year, :order => [:day, :month, :year] %>
		<p>
		<p>
			<%= f.label "Projeto" %>
			<%= collection_select(:tarefa, :projeto_id, Projeto.all, :id, :nome) %>
		<p>
		<br />	
		<%= f.submit :value => "Salvar" %>
	<% end %>
	<br/>
	

app/views/tarefas/create.html.erb
<h2>Tarefa criada com sucesso</h2>

app/views/tarefas/edit.html.erb
<h2> Editar Tarefa </h2>

<p class ="notice"><%= flash[:notice] %></p>

<%= render "form" %>

<%= link_to "Voltar" , tarefas_path %><br/>

app/views/tarefas/index.html.erb
<h2> Lista de Tarefas </h2>

<p class ="notice"><%= flash[:notice] %></p>

<%= link_to "Nova Tarefa" , new_tarefa_path %><br/><br/>

	<table>
		<tr>
			<th>Nome</th>
			<th>Responsavel</th>
			<th>Descrição</th>
			<th>Data de Entrega</th>
			<th>Projeto</th>
		</tr>
		<% @tarefas.each do |tarefa| %>
			<tr>
				<td><%= tarefa.nome %></td>
				<td><%= tarefa.responsavel %></td>
				<td><%= tarefa.descricao %></td>
				<td><%= tarefa.data_fim %></td>
				<td><%= link_para_o_projeto(tarefa) %></td>
				<td><%= link_to "Edit" , edit_tarefa_path(tarefa) %></td>
				<td><%= link_to "Deletar" , tarefa_path(tarefa) , :confirm => "Tem certeza?", :method => :delete %></td>
			</tr>
		<% end %>
	</table>

	<br/>
	<%= link_to "Projetos" , projetos_path %>

app/views/tarefas/new.html.erb
<h2> Nova Tarefa </h2>

	<%= form_for @tarefa do |f| %>
		<p>
			<%= f.label "Descrição" %> <br/>
			<%= f.text_area :descricao, :rows => 10 %>
		</p>
		<p>
			<%= f.label "Responsável" %>
			<%= f.text_field :responsavel %>
		</p>
		<p>
			<%= f.label "Data Conclusão" %>
			<%= f.date_select :data_fim, :start_year => Time.now.year, :order => [:day, :month, :year] %>
		<p>
		<br />	
		<%= f.submit :value => "Criar Tarefa" %>
	<% end %>
	<br/>
	<%= link_to "Voltar" , tarefas_path %><br/>